"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@sd)5_h3(j+(bm_@u6ns75z!loofk!l18x%lay@h%&+9*jtdt-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'channels_redis',
    'arb_agent',
    'forex'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'forex' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

ASGI_APPLICATION = "project.asgi.application"
 
# ── Django Channels / Redis ───────────────────────────────────────
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG":  {"hosts": [("127.0.0.1", 6379)]},
    }
}

# ── Celery ────────────────────────────────────────────────────────
CELERY_BROKER_URL        = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND    = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT    = ["json"]
CELERY_TASK_SERIALIZER   = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE          = "UTC"
CELERY_WORKER_CONCURRENCY = 1   # SQLite safe; remove when on Postgres

from celery.schedules import crontab

# ── Celery Queues ─────────────────────────────────────────────────
CELERY_TASK_QUEUES = {
    "trades": {
        "exchange": "trades",
        "routing_key": "trades",
    },
    "celery": {
        "exchange": "celery",
        "routing_key": "celery",
    },
}
CELERY_TASK_DEFAULT_QUEUE = "celery"

CELERY_BEAT_SCHEDULE = {
    "strategic-analysis": {
        "task":     "forex.run_strategic_analysis",
        "schedule": 1800,
        "args":     ("EURUSD",),
    },
    "hft-scan": {
        "task":     "forex.run_hft_scan",
        "schedule": 30,
        "args":     ("EURUSD",),
    },
    "strategic-analysis-btcusd": {   
        "task":     "forex.run_strategic_analysis",
        "schedule": 1800,
        "args":     ("BTCUSD",),
    },
    "hft-scan-btcusd": {             
        "task":     "forex.run_hft_scan",
        "schedule": 30,
        "args":     ("BTCUSD",),
    },
    "telegram-summary": {
        "task":     "forex.send_telegram_summary",
        "schedule": 1800,
    },
    "bridge-health": {
        "task":     "forex.check_bridge_health",
        "schedule": 300,
    },
}

# ── Logging ───────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "{asctime} {levelname} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "forex":     {"level": "DEBUG", "propagate": True},
        "arb_agent": {"level": "DEBUG", "propagate": True},
        "celery":    {"level": "INFO",  "propagate": True},
    },
}

# ── Deriv account mode (demo / live) ─────────────────────────────
# Switch to 'live' when you're ready for real trading.
# The codebase reads this for logging and Telegram message labelling.
import os as _os
DERIV_ACCOUNT_MODE = _os.getenv("DERIV_ACCOUNT_MODE", "demo")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
