# Generated by Django 6.0.3 on 2026-03-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(db_index=True, help_text='UUID matching the TradeCommand sent to FileBridge', max_length=36, unique=True)),
                ('ticket', models.BigIntegerField(blank=True, null=True)),
                ('symbol', models.CharField(default='EURUSD', max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('lot_size', models.FloatField(default=0.01)),
                ('sl_pips', models.IntegerField(default=0)),
                ('tp_pips', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('signal_source', models.CharField(choices=[('tradingview', 'TradingView'), ('manual', 'Manual (CLI)'), ('llm', 'LLM initiated'), ('test', 'Test / Dev')], default='tradingview', max_length=50)),
                ('signal_payload', models.JSONField(blank=True, help_text='Raw inbound JSON — never modified after write', null=True)),
                ('signal_indicators', models.JSONField(blank=True, help_text='Indicator snapshot extracted from signal_payload', null=True)),
                ('llm_approved', models.BooleanField(help_text='True=approved, False=rejected, None=gate not reached', null=True)),
                ('llm_reasoning', models.TextField(blank=True, help_text='Full reasoning text from the LLM', null=True)),
                ('llm_model_used', models.CharField(blank=True, help_text='e.g. groq/llama-3.3-70b', max_length=100, null=True)),
                ('llm_latency_ms', models.IntegerField(blank=True, help_text='Time the LLM gate took in milliseconds', null=True)),
                ('llm_confidence', models.IntegerField(blank=True, help_text='0-100 confidence score from the LLM', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the webhook hit Django')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When MT5 confirmed the order', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the position was closed', null=True)),
                ('execution_latency_ms', models.IntegerField(blank=True, help_text='ms from task dispatch to MT5 confirmation', null=True)),
                ('balance_at_entry', models.FloatField(blank=True, null=True)),
                ('equity_at_entry', models.FloatField(blank=True, null=True)),
                ('free_margin_at_entry', models.FloatField(blank=True, null=True)),
                ('open_trades_at_entry', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'LLM approved, awaiting execution'), ('EXECUTED', 'Executed on MT5'), ('REJECTED', 'Rejected by LLM gate'), ('CLOSED', 'Position closed'), ('ERROR', 'Execution error')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status'], name='forex_trade_status_271a1a_idx'), models.Index(fields=['signal_source'], name='forex_trade_signal__4eb592_idx'), models.Index(fields=['symbol'], name='forex_trade_symbol_3d4b92_idx'), models.Index(fields=['received_at'], name='forex_trade_receive_5323a8_idx')],
            },
        ),
    ]
